version: '3.7'
services:
  jenkins-slave:
    image: "zebrunner/jenkins-slave:${TAG_JENKINS_SLAVE}"
    container_name: jenkins-slave
    env_file:
      - variables.env
    ports:
     - "8000:8000"
    restart: always
