FROM alpine:edge AS alpine_edge

LABEL maintainer="Vadim Delendik <vdelendik@zebrunner.com>"

ENV DEBIAN_FRONTEND=noninteractive

#=============
# Set WORKDIR
#=============
WORKDIR /root

#==================
# General Packages
#==================
RUN apk add --no-cache \
    bash \
    openjdk17 \
    tzdata \
    curl \
    git \
    git-fast-import \
    openssh-client \
    bind-tools \
    gnupg \
    lsof && \
    rm -rf /var/lib/apt/lists/* /usr/lib/jvm/java-17-openjdk/demo /usr/lib/jvm/java-17-openjdk/man /usr/lib/jvm/java-17-openjdk/jre/demo /usr/lib/jvm/java-17-openjdk/jre/man

# ADB part
RUN apk add \
    android-tools \
    --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing

# kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    kubectl version --client

##===============
## Install Docker
##===============
#RUN apk add --no-cache docker openrc \
#    && rc-update add docker boot

#===============
# Set JAVA_HOME
#===============
ENV JAVA_HOME="/usr/lib/jvm/java-17-openjdk"
ENV PATH=$PATH:$JAVA_HOME/bin

#======================
# Install Jenkins swarm
#======================
ENV JENKINS_SLAVE_ROOT="/opt/jenkins"

USER root

RUN mkdir -p "$JENKINS_SLAVE_ROOT"
RUN mkdir -p /opt/apk

# Slave settings
ENV JENKINS_MASTER_USERNAME="jenkins" \
    JENKINS_MASTER_PASSWORD="jenkins" \
    JENKINS_MASTER_URL="http://jenkins:8080/" \
    JENKINS_SLAVE_MODE="exclusive" \
    JENKINS_SLAVE_NAME="swarm-$RANDOM" \
    JENKINS_SLAVE_WORKERS="1" \
    JENKINS_SLAVE_LABELS="" \
    AVD=""

# Set the lang, you can also specify it as as environment variable through docker-compose.yml
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8\
    LC_ALL=en_US.UTF-8

# Install Jenkins slave (swarm)
ADD files/swarm-client-3.34.jar /swarm-client.jar
ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]

FROM alpine:3.16.2 AS alpine_3_16_2

LABEL maintainer="Vadim Delendik <vdelendik@zebrunner.com>"

ENV DEBIAN_FRONTEND=noninteractive

#=============
# Set WORKDIR
#=============
WORKDIR /root

#==================
# General Packages
#==================
RUN apk add --no-cache \
    bash \
    openjdk17 \
    tzdata \
    curl \
    git \
    git-fast-import \
    openssh-client \
    bind-tools \
    gnupg \
    lsof && \
    rm -rf /var/lib/apt/lists/* /usr/lib/jvm/java-17-openjdk/demo /usr/lib/jvm/java-17-openjdk/man /usr/lib/jvm/java-17-openjdk/jre/demo /usr/lib/jvm/java-17-openjdk/jre/man


#==================
# MkDocs Packages
#==================
RUN apk add --no-cache --update py-pip \
	python3 \
	gcc \
	python3-dev \
	musl-dev && \
	pip install mkdocs mkdocs-material

# kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    kubectl version --client

#===============
# Install Docker
#===============
RUN apk add --no-cache docker openrc \
    && rc-update add docker boot

#===============
# Set JAVA_HOME
#===============
ENV JAVA_HOME="/usr/lib/jvm/java-17-openjdk"
ENV PATH=$PATH:$JAVA_HOME/bin

#======================
# Install Jenkins swarm
#======================
ENV JENKINS_SLAVE_ROOT="/opt/jenkins"

USER root

RUN mkdir -p "$JENKINS_SLAVE_ROOT"
RUN mkdir -p /opt/apk

# Slave settings
ENV JENKINS_MASTER_USERNAME="jenkins" \
    JENKINS_MASTER_PASSWORD="jenkins" \
    JENKINS_MASTER_URL="http://jenkins:8080/" \
    JENKINS_SLAVE_MODE="exclusive" \
    JENKINS_SLAVE_NAME="swarm-$RANDOM" \
    JENKINS_SLAVE_WORKERS="1" \
    JENKINS_SLAVE_LABELS="" \
    AVD=""

# Set the lang, you can also specify it as as environment variable through docker-compose.yml
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8\
    LC_ALL=en_US.UTF-8

# Install Jenkins slave (swarm)
ADD files/swarm-client-3.34.jar /swarm-client.jar
ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]

FROM jenkins/inbound-agent:latest-jdk17 AS jnpl

LABEL maintainer="Vadim Delendik <vdelendik@zebrunner.com>"

ENV DEBIAN_FRONTEND=noninteractive

USER root

#=============
# Set WORKDIR
#=============
WORKDIR /root

#==================
# General Packages
#==================
RUN apt-get -qqy update && \
	apt-get -qqy --no-install-recommends install lsof android-tools-adb

USER ${user}
WORKDIR /home/${user}
ENTRYPOINT ["jenkins-agent"]

FROM python:3.7.12-slim AS python

LABEL maintainer="Vadim Delendik <vdelendik@zebrunner.com>"

ENV DEBIAN_FRONTEND=noninteractive

#=============
# Set WORKDIR
#=============
WORKDIR /root

#==================
# General Packages
#==================
RUN apt-get update && \
    apt-get install -y -q \
    bash \
    openjdk-17-jdk \
    tzdata \
    curl \
    git \
    openssh-client && \
    rm -rf /var/lib/apt/lists/* /usr/lib/jvm/java-17-openjdk/demo /usr/lib/jvm/java-17-openjdk/man /usr/lib/jvm/java-17-openjdk/jre/demo /usr/lib/jvm/java-17-openjdk/jre/man

#===============
# Set JAVA_HOME
#===============
ENV JAVA_HOME="/usr/lib/jvm/java-17-openjdk"
ENV PATH=$PATH:$JAVA_HOME/bin

#======================
# Install Jenkins swarm
#======================
ENV JENKINS_SLAVE_ROOT="/opt/jenkins"

USER root

RUN mkdir -p "$JENKINS_SLAVE_ROOT"
RUN mkdir -p /opt/apk

# Slave settings
ENV JENKINS_MASTER_USERNAME="jenkins" \
    JENKINS_MASTER_PASSWORD="jenkins" \
    JENKINS_MASTER_URL="http://jenkins:8080/" \
    JENKINS_SLAVE_MODE="exclusive" \
    JENKINS_SLAVE_NAME="swarm-$RANDOM" \
    JENKINS_SLAVE_WORKERS="1" \
    JENKINS_SLAVE_LABELS="" \
    AVD=""

# Set the lang, you can also specify it as as environment variable through docker-compose.yml
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8\
    LC_ALL=en_US.UTF-8

# Install Jenkins slave (swarm)
ADD files/swarm-client-3.34.jar /swarm-client.jar
ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
